name: CI/CD PipeLine

on:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build Frontend Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"

      - run: |
          cd frontend 
          npm i

      - run: |
          cd frontend
          npm run build

      - uses: actions/upload-pages-artifact@v1
        with:
          path: frontend/build

      # - id: build-publish
      #   uses: bitovi/github-actions-react-to-github-pages@v1.2.2
      #   with:
      #     path: build # change to your build folder
